### ISSUE TITLE
some err when I run python setup.py install

### ISSUE THREAD

**Issue by CatoDee** [mikegrudic/CrunchSnaps#1]
Hi Michael

I git clone this code and run the setup.py to install the package: python setup.py install. 
But there is an error here. I try to install amuse-fresco with pip as well. But it also shows this error. 
I don't know how to deal with it. Could you help me?

## the error message:

Installed /Users/yihuan/Software/miniforge3/lib/python3.9/site-packages/aggdraw-1.3.18.post0-py3.9-macosx-11.0-arm64.egg
Searching for amuse-fresco
Reading https://pypi.org/simple/amuse-fresco/
Downloading https://files.pythonhosted.org/packages/8f/cf/73a4fce557630d87a64a59db711ce5be05a4b63e5f6c5e180a88eac1913b/amuse-fresco-2023.3.0.tar.gz#sha256=9df75976fc931b8315fc425b1eaf53f1f80c67ee71745dc702420b20322d0bfc
Best match: amuse-fresco 2023.3.0
Processing amuse-fresco-2023.3.0.tar.gz
Writing /var/folders/9w/f6hrq1ts03l3rldq00x8lpb40000gn/T/easy_install-ocdfbdb4/amuse-fresco-2023.3.0/setup.cfg
Running amuse-fresco-2023.3.0/setup.py -q bdist_egg --dist-dir /var/folders/9w/f6hrq1ts03l3rldq00x8lpb40000gn/T/easy_install-ocdfbdb4/amuse-fresco-2023.3.0/egg-dist-tmp-py5h7ra7
.....
    assert isinstance(value, dict), "version_keyword expects a dict or True"
AssertionError: version_keyword expects a dict or True

**Comment by mikegrudic** [comment]
Hi,

I also have this problem when trying to install the upstream dependency amuse-fresco with pip in any environment, totally independently of CrunchSnaps.  Please open an issue [there](https://github.com/rieder/amuse-fresco).

Mike
